services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    network_mode: host
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 784:784/udp
      - 853:853/tcp
      - 3001:3000/tcp
      - 84:80/tcp
      - 443:443/tcp
    volumes:
      - /home/mi/docker/adguardhome/workdir:/opt/adguardhome/work
      - /home/mi/docker/adguardhome/confdir:/opt/adguardhome/conf
    restart: unless-stopped
