networks:
  appnet:
    external: true

services:
  # ─── VPN gateway ───────────────────────────────────────────
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    hostname: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      - appnet
    ports:
      - 8080:8080 # qBittorrent Web UI
      - 6881:6881 # qBittorrent torrenting
      - 9696:9696 # Prowlarr
      - 8191:8191 # flaresolverr
    volumes:
      - ${ARRPATH}/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_IP}
      - UPDATER_PERIOD=24h
      - SERVER_CITIES=Stockholm
      - FIREWALL_OUTBOUND_SUBNETS=172.21.0.0/24
      - TZ=${TZ}
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 60s
      timeout: 20s
      retries: 5
    restart: unless-stopped

  # ─── Prowlarr ──────────────────────────────────────────────
  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    volumes:
      - ${ARRPATH}/Prowlarr/config:/config
      - ${ARRPATH}/Prowlarr/backup:/data/Backup
      - ${ARRPATH}/Downloads:/downloads
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    depends_on:
      - gluetun
    network_mode: service:gluetun

  # ─── Sonarr ────────────────────────────────────────────────
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    networks:
      - appnet
    ports:
      - 8989:8989
    volumes:
      - ${ARRPATH}/Sonarr/config:/config
      - ${ARRPATH}/Sonarr/backup:/data/Backup
      - ${ARRPATH}/Sonarr/tvshows:/data/tvshows
      - ${ARRPATH}/Downloads:/downloads
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}

  # ─── Radarr ────────────────────────────────────────────────
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    networks:
      - appnet
    ports:
      - 7878:7878
    volumes:
      - ${ARRPATH}/Radarr/config:/config
      - ${ARRPATH}/Radarr/movies:/data/movies
      - ${ARRPATH}/Radarr/backup:/data/Backup
      - ${ARRPATH}/Downloads:/downloads
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}

  # ─── Homarr ────────────────────────────────────────────────
  homarr:
    image: ghcr.io/ajnart/homarr:latest
    container_name: homarr
    networks:
      - appnet
    ports:
      - 7575:7575
    volumes:
      - ${ARRPATH}/Homarr/configs:/app/data/configs
      - ${ARRPATH}/Homarr/icons:/app/public/icons
      - ${ARRPATH}/Homarr/data:/data
    restart: unless-stopped
    environment:
      - TZ=${TZ}

  # ─── qBittorrent ───────────────────────────────────────────
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    volumes:
      - ${ARRPATH}/qbittorrent/config:/config
      - ${ARRPATH}/Downloads:/downloads
    environment:
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}s
    restart: unless-stopped
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    network_mode: service:gluetun
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 60s
      retries: 3
      start_period: 20s
      timeout: 10s

  # ─── Bazarr ────────────────────────────────────────────────
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    networks:
      - appnet
    ports:
      - 6767:6767
    volumes:
      - ${ARRPATH}/bazarr:/config
      - ${ARRPATH}/bazarr/data:/data
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}

  # ─── Jellyseerr ────────────────────────────────────────────
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    networks:
      - appnet
    ports:
      - 5055:5055
    volumes:
      - ${ARRPATH}/jellyseerr:/app/config
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}

  # ─── Flaresolverr ────────────────────────────────────────────
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    restart: unless-stopped
    network_mode: service:gluetun
