networks:
  arrnet:
    external: true

services:
  # ─── VPN gateway ───────────────────────────────────────────
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    hostname: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      - arrnet
    ports:
      - 8080:8080   # qBittorrent Web UI
      - 6881:6881   # qBittorrent torrenting
      - 9696:9696   # Prowlarr
      - 8191:8191   # flaresolverr
    volumes:
      - ${ARRPATH}/gluetun:/gluetun
    env_file: stack.env
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 60s
      timeout: 20s
      retries: 5
    restart: unless-stopped

  # ─── Prowlarr ──────────────────────────────────────────────
  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    volumes:
      - ${ARRPATH}/prowlarr/config:/config
      - ${DATAPATH}:/data
    restart: unless-stopped
    env_file: stack.env
    depends_on:
      - gluetun
    network_mode: service:gluetun

  # ─── sonarr ────────────────────────────────────────────────
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    networks:
      - arrnet
    ports:
      - 8989:8989
    volumes:
      - ${ARRPATH}/sonarr/config:/config
      - ${DATAPATH}:/data
    restart: unless-stopped
    env_file: stack.env
      
  # ─── radarr ────────────────────────────────────────────────
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    networks:
      - arrnet
    ports:
      - 7878:7878
    volumes:
      - ${ARRPATH}/radarr/config:/config
      - ${DATAPATH}:/data
    restart: unless-stopped
    env_file: stack.env
      
  # ─── homarr ────────────────────────────────────────────────
  homarr:
    image: ghcr.io/ajnart/homarr:latest
    container_name: homarr
    networks:
      - arrnet
    ports:
      - 7575:7575
    volumes:
      - ${ARRPATH}/homarr/configs:/app/data/configs
      - ${ARRPATH}/homarr/icons:/app/public/icons
      - ${ARRPATH}/homarr/data:/data
    restart: unless-stopped
    env_file: stack.env
      
  # ─── qBittorrent ───────────────────────────────────────────
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    volumes:
      - ${ARRPATH}/qbittorrent/config:/config
      - ${DATAPATH}/downloads:/downloads
    env_file: stack.env
    restart: unless-stopped
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    network_mode: service:gluetun
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 60s
      retries: 3
      start_period: 20s
      timeout: 10s
      
  # ─── Bazarr ────────────────────────────────────────────────
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    networks:
      - arrnet
    ports:
      - 6767:6767
    volumes:
      - ${ARRPATH}/bazarr:/config
      - ${DATAPATH}:/data
    restart: unless-stopped
    env_file: stack.env

 # ─── Flaresolverr ────────────────────────────────────────────
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
    env_file: stack.env
    restart: unless-stopped
    network_mode: service:gluetun