services:
  filebrowser:
      image: filebrowser/filebrowser:latest
      container_name: filebrowser
      ports:
        - "8081:80"
      volumes:
        - /home/mi:/srv             # root of library
        - /home/mi/docker/filebrowser/data:/data   # File Browser user data
        - /home/mi/docker/filebrowser/config:/config
        - /home/mi/docker/filebrowser/db/filebrowser.db:/database/filebrowser.db
      restart: unless-stopped
      env_file: files.env
