services:
  filebrowser:
      image: filebrowser/filebrowser:latest
      container_name: filebrowser
      ports:
        - "8081:80"
      volumes:
        - ${HOMEPATH}:/srv             # root of library
        - ${DOCKER}/filebrowser/data:/data   # File Browser user data
        - ${DOCKER}/filebrowser/config:/config
        - ${DOCKER}/filebrowser/db/filebrowser.db:/database/filebrowser.db
      restart: unless-stopped
      env_file: stack.env
