networks:
  appnet:
    external: true

services:
  # ─── Jellyfin ──────────────────────────────────────────────
  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    networks:
      - appnet
    ports:
      - "8096:8096"
    volumes:
      - ${MEDIAPATH}/Jellyfin/config:/config
      - ${ARRPATH}/Radarr/movies:/data/Movies
      - ${ARRPATH}/Sonarr/tvshows:/data/TVShows
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8096/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}

  # ─── Internet Radio Manager ────────────────────────────────
  azuracast:
    image: ghcr.io/azuracast/azuracast:stable
    container_name: azuracast
    networks:
      - appnet
    ports:
      - "9080:80"
      - "8443:443"
      - "2222:2022"
      - "8800:8000"
      - "8805:8005"
    environment:
      - APPLICATION_ENV=production
      - AUTO_ASSIGN_PORT_MIN=8000
      - AUTO_ASSIGN_PORT_MAX=8499
      - MYSQL_RANDOM_ROOT_PASSWORD=1
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${MEDIAPATH}/azuracast/config:/var/azuracast/config
      - ${MEDIAPATH}/azuracast/stations:/var/azuracast/stations
      - ${MEDIAPATH}/azuracast/playlists:/var/azuracast/playlists
      - ${MEDIAPATH}/azuracast/logs:/var/azuracast/logs
      - ${MEDIAPATH}/azuracast/db_data:/var/lib/mysql
    restart: unless-stopped

  # ─── File Browser ───────────────────────────────────────────
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    networks:
      - appnet
    ports:
      - "8081:80" # expose File Browser UI on host port 8081
    volumes:
      - ${ROOTPATH}:/srv # root of media library
      - ${MEDIAPATH}/filebrowser/data:/data # File Browser user data
      - ${MEDIAPATH}/filebrowser/config:/config
      - ${MEDIAPATH}/filebrowser/db/filebrowser.db:/database/filebrowser.db
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'curl -s -f http://localhost:80/health | grep -q ''"status":"OK"'' || exit 1',
        ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
