services:
  # ─── Nginx Proxy Manager ───────────────────────────────────
  proxy:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - "81:81"
      - "80:80"
      - "443:443"
    volumes:
      - ${PROXYPATH}/npm/data:/data
      - ${PROXYPATH}/letsencrypt:/etc/letsencrypt
#    healthcheck:
#      test: ["CMD", "/usr/bin/check-health"]
#      interval: 10s
#      timeout: 3s


  # ─── Tailscale VPN ─────────────────────────────────────────
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    hostname: tailscale
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_EXTRA_ARGS=--advertise-tags=tag:container --accept-routes
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - type: bind
        source: ${PROXYPATH}/tailscale/state
        target: /var/lib/tailscale
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun
    network_mode: host
    restart: unless-stopped
    command: >
      sh -c "tailscaled & sleep 5 && tailscale up --advertise-tags=tag:container --accept-routes"
#    healthcheck:
#      test: tailscale status --peers=false --json | grep -q 'Online.*true'



  # ─── Local DNS for arweb.dev ───────────────────────────────
  dnsmasq:
    image: dockurr/dnsmasq:latest
    container_name: dnsmasq
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    environment:
      DNS1: "1.1.1.1"        # Cloudflare primary
      DNS2: "1.0.0.1"        # Cloudflare secondary
    volumes:
      - ${PROXYPATH}/dnsmasq.d:/etc/dnsmasq.d:ro

#    healthcheck:
#      test: ["CMD", "dnsmasq", "--test"]
#      interval: 30s
#      timeout: 5s
#      retries: 3