services:
  # ─── Nginx Proxy Manager ───────────────────────────────────
  proxy:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - "81:81"
      - "80:80"
      - "443:443"
    volumes:
      - /home/mi/docker/npm/data:/data
      - /home/mi/docker/letsencrypt:/etc/letsencrypt
    healthcheck:
      test: ["CMD", "/usr/bin/check-health"]
      interval: 30s
      timeout: 3s
    env_file: proxy.env